helloapp:
  build: ./hello-app
  command: "python hello.py"
  volumes:
    - ./hello-app/src:/opt/hello-app

goodbyeapp:
  build: ./goodbye-app
  command: "python goodbye.py"
  volumes:
    - ./goodbye-app/src:/opt/goodbye-app

lime:
  build: ../lime
  command: "python app.py"
  env_file: ../lime/.env
  volumes:
    - ../lime:/opt/lime

facade:
  build: ../facade
  command: "python app.py"
  env_file: ../facade/.env
  volumes:
    - ../facade:/opt/facade

proxy:
  build: ./proxy
  ports:
    - "80:80"
  volumes:
    - ./proxy/sites-enabled:/etc/nginx/sites-enabled
  links:
    - helloapp
    - goodbyeapp
    - facade
    - lime
